server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc-security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Ycy13579
    driver-class-name: com.mysql.cj.jdbc.Driver