server:
  port: 9090
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc-security?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Ycy13579
    driver-class-name: com.mysql.cj.jdbc.Driver